"""fix to Cukier

Revision ID: c9b19142874e
Revises: d10a76380f9c
Create Date: 2020-03-01 13:18:08.041594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b19142874e'
down_revision = 'd10a76380f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciasto', sa.Column('cukier', sa.String(length=254), nullable=True))
    op.add_column('ciasto', sa.Column('syrop', sa.String(length=254), nullable=True))
    op.add_column('ciasto', sa.Column('ziola', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ciasto', 'ziola')
    op.drop_column('ciasto', 'syrop')
    op.drop_column('ciasto', 'cukier')
    # ### end Alembic commands ###
