"""ciasto

Revision ID: cd6a678db48f
Revises: 74c0714d1adc
Create Date: 2020-02-29 09:58:48.870105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6a678db48f'
down_revision = '74c0714d1adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partia', sa.String(length=64), nullable=True),
    sa.Column('ilosc', sa.Integer(), nullable=True),
    sa.Column('stan', sa.Integer(), nullable=True),
    sa.Column('cena', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciasto_ilosc'), 'ciasto', ['ilosc'], unique=False)
    op.create_index(op.f('ix_ciasto_partia'), 'ciasto', ['partia'], unique=False)
    op.create_index(op.f('ix_ciasto_timestamp'), 'ciasto', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ciasto_timestamp'), table_name='ciasto')
    op.drop_index(op.f('ix_ciasto_partia'), table_name='ciasto')
    op.drop_index(op.f('ix_ciasto_ilosc'), table_name='ciasto')
    op.drop_table('ciasto')
    # ### end Alembic commands ###
