"""users table

Revision ID: d10a76380f9c
Revises: 
Create Date: 2020-03-01 13:06:41.683249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10a76380f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partia', sa.String(length=64), nullable=True),
    sa.Column('ilosc', sa.Float(), nullable=True),
    sa.Column('stan', sa.Float(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciasto_ilosc'), 'ciasto', ['ilosc'], unique=False)
    op.create_index(op.f('ix_ciasto_partia'), 'ciasto', ['partia'], unique=False)
    op.create_index(op.f('ix_ciasto_timestamp'), 'ciasto', ['timestamp'], unique=False)
    op.create_table('cukier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dostawa', sa.String(length=64), nullable=True),
    sa.Column('ilosc', sa.Float(), nullable=True),
    sa.Column('zuzyte', sa.Float(), nullable=True),
    sa.Column('stan', sa.Float(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cukier_dostawa'), 'cukier', ['dostawa'], unique=False)
    op.create_index(op.f('ix_cukier_ilosc'), 'cukier', ['ilosc'], unique=False)
    op.create_index(op.f('ix_cukier_timestamp'), 'cukier', ['timestamp'], unique=False)
    op.create_table('syrop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dostawa', sa.String(length=64), nullable=True),
    sa.Column('ilosc', sa.Float(), nullable=True),
    sa.Column('zuzyte', sa.Float(), nullable=True),
    sa.Column('stan', sa.Float(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syrop_dostawa'), 'syrop', ['dostawa'], unique=False)
    op.create_index(op.f('ix_syrop_ilosc'), 'syrop', ['ilosc'], unique=False)
    op.create_index(op.f('ix_syrop_timestamp'), 'syrop', ['timestamp'], unique=False)
    op.create_table('ziola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dostawa', sa.String(length=64), nullable=True),
    sa.Column('ilosc', sa.Float(), nullable=True),
    sa.Column('zuzyte', sa.Float(), nullable=True),
    sa.Column('stan', sa.Float(), nullable=True),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ziola_dostawa'), 'ziola', ['dostawa'], unique=False)
    op.create_index(op.f('ix_ziola_ilosc'), 'ziola', ['ilosc'], unique=False)
    op.create_index(op.f('ix_ziola_timestamp'), 'ziola', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ziola_timestamp'), table_name='ziola')
    op.drop_index(op.f('ix_ziola_ilosc'), table_name='ziola')
    op.drop_index(op.f('ix_ziola_dostawa'), table_name='ziola')
    op.drop_table('ziola')
    op.drop_index(op.f('ix_syrop_timestamp'), table_name='syrop')
    op.drop_index(op.f('ix_syrop_ilosc'), table_name='syrop')
    op.drop_index(op.f('ix_syrop_dostawa'), table_name='syrop')
    op.drop_table('syrop')
    op.drop_index(op.f('ix_cukier_timestamp'), table_name='cukier')
    op.drop_index(op.f('ix_cukier_ilosc'), table_name='cukier')
    op.drop_index(op.f('ix_cukier_dostawa'), table_name='cukier')
    op.drop_table('cukier')
    op.drop_index(op.f('ix_ciasto_timestamp'), table_name='ciasto')
    op.drop_index(op.f('ix_ciasto_partia'), table_name='ciasto')
    op.drop_index(op.f('ix_ciasto_ilosc'), table_name='ciasto')
    op.drop_table('ciasto')
    # ### end Alembic commands ###
